name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.81.112.229 << 'EOF'
          # Actualizar paquetes e instalar dependencias necesarias
          echo "Actualizando paquetes e instalando dependencias..."
          sudo apt-get update -y
          sudo apt-get install -y apache2 git unzip

          # Iniciar y habilitar el servicio Apache
          echo "Configurando Apache..."
          sudo systemctl start apache2
          sudo systemctl enable apache2

          # Verificar y crear el directorio /var/www/html si no existe
          echo "Verificando el directorio /var/www/html..."
          if [ ! -d "/var/www/html" ]; then
              echo "El directorio no existe, creando..."
              sudo mkdir -p /var/www/html
          fi

          # Ajustar permisos en el directorio para el usuario actual
          sudo chown -R ubuntu:ubuntu /var/www/html
          sudo chmod -R 755 /var/www/html

          # Eliminar contenido existente en el directorio /var/www/html
          echo "Eliminando contenido previo en /var/www/html..."
          sudo rm -rf /var/www/html/* /var/www/html/.git

          # Clonar el repositorio en el directorio
          echo "Clonando el repositorio..."
          git clone https://github.com/antoUwU-10/Ml.git /tmp/ml-temp

          # Verificar si el clon fue exitoso
          if [ $? -ne 0 ]; then
              echo "Error al clonar el repositorio. Por favor verifica el enlace."
              exit 1
          fi

          # Mover el contenido al directorio /var/www/html
          echo "Moviendo el contenido al directorio /var/www/html..."
          sudo mv /tmp/ml-temp/* /var/www/html
          sudo mv /tmp/ml-temp/.git /var/www/html

          # Limpiar el directorio temporal
          rm -rf /tmp/ml-temp

          # Asegurarse de que el archivo index.html esté presente
          echo "Verificando que el archivo index.html esté presente..."
          if [ ! -f "/var/www/html/index.html" ]; then
              echo "No se encontró el archivo index.html. Asegúrate de que esté en el repositorio."
              exit 1
          fi

          # Ajustar permisos para que Apache pueda acceder
          echo "Ajustando permisos para Apache..."
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html

          # Reiniciar Apache para cargar los cambios
          echo "Reiniciando Apache..."
          sudo systemctl restart apache2

          # Verificar que Apache esté funcionando correctamente
          echo "Verificando el estado de Apache..."
          if ! sudo systemctl status apache2 | grep -q "active (running)"; then
              echo "Apache no está funcionando correctamente."
              exit 1
          fi

          # Verificar que el sitio web sea accesible
          echo "Verificando que la página web esté accesible..."
          if ! curl -I http://localhost 2>/dev/null | grep -q "200 OK"; then
              echo "La página web no está accesible. Verifica la configuración."
              exit 1
          fi
          EOF
