name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.89.2.115 << 'EOF'
          cd /var/www/html
          #sudo rm -rf *
          if [ -d ".git" ]; then
              # Si es un repositorio git, hacer pull 
              git pull origin main
          else
              # Si no existe, clonar el repositorio
              git clone https://github.com/antoUwU-10/Ml.git .
          fi
          EOF
