name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.90.210.202 << 'EOF'
          echo "Verificando el directorio /var/www/html"
          if [ ! -d "/var/www/html" ]; then
              echo "El directorio no existe, creando..."
              sudo mkdir -p /var/www/html
              sudo chown ubuntu:ubuntu /var/www/html
          fi
          cd /var/www/html
          echo "Directorio actual: $(pwd)"
          if [ -d ".git" ]; then
              echo "Repositorio Git encontrado. Haciendo pull..."
              git pull origin main
          else
              echo "No es un repositorio Git. Clonando el repositorio..."
              git clone https://github.com/antoUwU-10/Ml.git .
          fi
          EOF